### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by elldissin** [redmcg/wine#11]
Hello,
I am pretty new to running games with wine. So I wanted to start ED from steamplay using the Proton 4.2 from this guide, but crashed into a problem I cannnot solve on my own: after I go through all the steps and press Play button for ED in Steam, it thinks for a while and then gives me the following error window:

Error during application startup
Exception initialising application
Illegal characters in path

One thing that is worth mentioning is that I have installed the game on other drive, in a separate steam library folder which is dedicated for games I run from steam in Linux, but this is NTFS drive mounted in my Ubuntu installation (I have too small SSD in Ubuntu for this). Can this be a problem?
Thank you in advance!

**Comment by redmcg** [comment]
I've not seen this error before - but it looks like a windows one:
https://stackoverflow.com/questions/3315983/illegal-character-in-path

What's the path to your install location?

**Comment by elldissin** [comment]
Thanks for quick reply! The path to that mounted NTFS drive is
/media/light/D0CC07C3CC07A338/Games/ubuntu_steam/steamapps/common/Elite Dangerous
I presume the space between "Elite" and "Dangerous" should not count as illegal? Its created so by steam itself...
And yes, the error window visual style is Windows's OS one, so it probably comes from there

**Comment by redmcg** [comment]
Yeah - I don't see anything wrong there. We might need a log. See here for instructions:
https://github.com/ValveSoftware/Proton/blob/proton_4.2/README.md#runtime-config-options

**Comment by elldissin** [comment]
Here is the link to my log: https://drive.google.com/open?id=1khMZutg9dLnGkCSQa6h5wc2VHk0HuAeJ
Hope I did it correctly. I chose ED "Properties" in Steam, then "Set launch options", and pasted "PROTON_LOG=1 %command%" there. And got the above file.

**Comment by redmcg** [comment]
Yep - that's the one. Thanks for that.

Unfortunately the only thing of interest I could find in there was this:
> 38569.448:0035:0036:err:eventlog:ReportEventW
> L"Application: EDLaunch.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an internal error in the .NET Runtime at IP 000006447F2064DC (000006447F100000) with exit code 80131506."

I'm not familiar with Windows exit codes - but a Google search produced this:
https://stackoverflow.com/a/4367865

So it sounds like a memory corruption issue occurring within the memory managed by dotnet40. I'm not sure what would cause that - so the only suggestion I have is to try to reinstall your prefix. You can follow the instructions here:
https://github.com/redmcg/wine/wiki#the-official-build-of-proton-42-runs-ed

**Comment by elldissin** [comment]
OK, I will dig it further. Will try to repeat the installation and prefix process, maybe I did something wrong. I'm closing this issue, as it seems to be not related, but if I fix it somehow, will try to report back in order to let everyone know ;)
Thank you for support anyway!

**Comment by elldissin** [comment]
Sorry for beginner's question, but by the way, should I use 64 bit wineprefix for ED to run under proton 4.2? And Is there a way to verify if dotnet40 is properly installed into prefix? 
 I studied the log during installing things via winetricks and noted this:
` This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better`
So I was thinking that this might be related to my problem.

UPD:
I tried doing everything from zero and noted the following error also:
![Screenshot from 2019-04-21 21-37-01](https://user-images.githubusercontent.com/13391608/56474412-14436d00-6482-11e9-8d7b-2bec6748f6b4.png)
Feels like indeed my dotnet40 is not installed properly. Is there a way I can fix it?

**Comment by redmcg** [comment]
You need to use a 64-bit prefix (as ED is a 64-bit game). I think that warning may be applicable to older versions of Wine (as dotnet40 appears to work fine in 64-bit on recent versions).

That rundll32.exe error is also standard when you change Wine versions (i.e. from the version you used to install dotnet40 to the proton version) and can be safely ignored.

The only problems I'm aware of when installing dotnet40 are due to:
1. Using an old version of `wine` or `winetricks` (you can check both with the `--version` parameter); or
2. Running out of file handles (usually a result of running ESYNC with a small value for the 'open files' user limit)

ESYNC has only just been added to Wine Staging 4.6 and is disabled by default - so it's probably not that. So the only suggestion I have is to check your versions of wine and winetricks with:
```
wine --version
winetricks --version
```

**Comment by elldissin** [comment]
I did some progress in studying on wine topic, but now whatever I do I am stuck at same error. There are many debates on forums about how bad dotnet is with 64bit and how to work it around, but honestly I don't get the trick...
`0014:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0014:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0019:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
001c:fixme:heap:RtlSetHeapInformation 0x340000 0 0x22e390 4 stub
001c:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
001f:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
0009:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"EDLaunch.exe" cannot be loaded
0009:err:module:LdrInitializeThunk Importing dlls for L"Z:\\media\\light\\D0CC07C3CC07A338\\Games\\ubuntu_steam\\steamapps\\common\\Elite Dangerous\\EDLaunch.exe" failed, status c0000135
`
And this mscoree.dll is not found regardless of .NET state. I have tried so far:
- installing it by winetricks dotnet40
- installing it by winetricks -q dotnet40
- installing it manually by wine dotNetFx40_Full_x86_x64.exe (the downloaded file)
- installing it by winetricks dotnet40 while having fresh prefix made with `WINEDLLOVERRIDES="mscoree=d;mshtml=d" wineboot -i` 
- the mscoree.dll file is present in both windows/system32 and windows/syswow64

wine --version returns wine-4.6 (Staging)
winetricks --version returns 20190310-next
so I am assuming all fine with versions, right?

Maybe someone knows what I am doing wrong here...anyway already this progress gave me better understanding :D

**Comment by redmcg** [comment]
Those wine and winetricks versions look fine (although I haven't tried 4.6 staging myself).

Maybe you could try something a bit different. You could try this custom build of Proton:
https://github.com/redmcg/wine/releases/tag/ED_Proton_3.16-7_Beta

The instructions on how to install it can be found here:
https://github.com/redmcg/wine/wiki#to-install-the-legacy-custom-build

Those instructions are for ED 3.16-8 Beta, but I recommend ED 3.16-7 Beta as it installs vcrun2015 (which is required if you want to use the stock 4.2-3 Beta). The only difference in the install is the tarball you download.

**Comment by elldissin** [comment]
Thank you very much!
This ED_Proton_3.16-7_Beta indeed did the work. I followed the instructions, had to do it couple of times to make sure everything followed correctly. 
Also at some point (probably reference to warning in the instruction beginning xD) I ended up with ED deleted completely, so had to dowload it again with steam. But who knows, maybe that was also crucial moment for the success.
I was able to play ED Horizons with it. Did couple of jumps, parking etc.

P.S. Still don't know why 4.2 build didn't work, but maybe I give it a try once in future.

**Comment by redmcg** [comment]
Excellent - glad you got it working. I haven't tried creating a new prefix with the more recent versions of Wine. It could be they introduced a regression. When I get a chance I'll try it out and update my instructions if I find anything.

When you do want to try 4.2 - you shouldn't need to create a new prefix. It should just work out of the box now that you have dotnet40 and vcrun2015 installed

**Comment by redmcg** [comment]
@elldissin I looked in to this and it looks like wine 4.6 changed how `wine-mono` is installed. `dotnet40` won't install when `wine-mono` is installed and `winetricks` needed to be changed to cater for how 4.6 did the `wine-mono` install.

So you need the latest version of `winetricks` with wine 4.6 or later. Unfortunately the `winetricks` version wasn't incremented with this change, so you can't tell if it will work or not just by the version.

So I think that's why you were having problems with 4.2. You needed either:
- a later version of `winetricks`; or
- an earlier version of wine

I've updated the wiki to reflect these findings.

**Comment by elldissin** [comment]
Thanks for digging it more, I will try it once. I am glad my problem really caused some new discoveries
