### ISSUE TITLE
Launcher launches, but game doesn't

### ISSUE THREAD

**Issue by breach-candy** [redmcg/wine#12]
Hello, I've been following the guide in the wiki tab, and have completed most of it. The launcher opens, I press play, a window pops up and the closes immediately. This is what is included in the log: 
https://pastebin.com/vaYtVnia

**Comment by redmcg** [comment]
Hi @brch-cndy. I'll need the Proton Log to be able to investigate.

Instructions on how to switch on the Proton Log and where the log is written to can be found here:
https://github.com/ValveSoftware/Proton#runtime-config-options

It'll also help to know:
1. what OS you're running;
2. what graphics card you're using; and
3. what graphics driver (and version) you're running

**Comment by breach-candy** [comment]
OS: Arch(BTW)
GFX Card: I use intel 630 for running my DE, but I run elite off my 1660ti
Driver: nvidia-440.82-11

log: https://drive.google.com/file/d/1grL7bCGTzZqXXCmiQ9ITyAGKb90CFlTD/view?usp=sharing
Sorry it's a 25mb file, I couldn't upload it to pastebin or gists.

**Comment by redmcg** [comment]
The most interesting part in that log was this:
```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  7 (X_GLXQueryVersion)
  Serial number of failed request:  362
  Current serial number in output stream:  362
```

I haven't seen that before (and it doesn't mean much to me), but a quick Google search led me here:
https://superuser.com/questions/1470087/vulkan-is-failing-on-linux-with-badlength-poly-request-too-large-or-internal-xl

Are you using Bumblebee?

Edit: My assumption at the moment is this is an issue with Vulkan running correctly. Are you able to get `vulkaninfo` running with info for your 1660ti?

Edit2: Another way to test if Vulkan is the issue is to run the game with PROTON_USE_WINED3D=1 (as described [here](https://github.com/ValveSoftware/Proton#runtime-config-options))

**Comment by breach-candy** [comment]
Yeah, I'm using bumblebee. I'm not sure whether vulkaninfo works, but when I run the command(on the nvidia card ofc) I get this message: `[1]    14121 segmentation fault (core dumped)  vulkaninfo`

When booting my entire system onto the nvidia card(along with elite, steam, and elite launcher), the game launches but it's only a black window

Also, I do have primus_vk installed.

Sorry if I'm not giving the best info, I'm new and not very good at this xd

**Comment by redmcg** [comment]
OK - it does seem like an issue with Vulkan. Not sure why you would get a black window when booting with the nvidia card though. Does `vulkaninfo` run when you do this?

But this means the game should run with PROTON_USE_WINED3D=1 (as described [here](https://github.com/ValveSoftware/Proton#runtime-config-options)) - but performance is pretty poor and the lighting is all wrong.

So you'll want to get Vulkan working (which you can confirm by running `vulkaninfo`; which should return a big list of Vulkan features). Unfortunately I can't really help with that as I've not used Arch and not really experiemented with Bumblebee much.

You might want to jump on an Arch forum and see if someone there can help.

**Comment by breach-candy** [comment]
Using PROTON_USE_WINED3D=1 worked, and as you said lighting is wonk and performance is wack. I'll attempt to get vulkan working now. Thanks for your help!

EDIT: I'll post the answer here so that if anyone has this problem they'll be able to fix it.
