### ISSUE TITLE
ED unstable crash a lot or after launch doesn't start

### ISSUE THREAD

**Issue by weberkai** [redmcg/wine#13]
Hi!

ED was crashing a lot, and I was always  getting stuck in black screen after launcher.

"PROTON_NO_ESYNC=1 %command%" seems to solve it, but it adds various short moment freezes. Like pausing to load textures to GPU...

I've then checked ulimit -Hn and ulimit -Sn... They were too small... I've set them both to 1048576. (In my OS this is done in /etc/initscript , but this can vary...)

Increasing hard and soft limits allowed me to remove PROTON_NO_ESYNC=1 from launcher...

I'm telling here, because maybe you could advice this in the troubleshooting section:

ED needs a lot of file descriptors.
Check ulimit -Hn and ulimit -Sn and increase both hard and soft limits to 1048576.

Thank you very much!

**Comment by redmcg** [comment]
Thanks for this. I've added a note to the troubleshooting section:
https://github.com/redmcg/wine/wiki#game-is-crashing-a-lot-or-getting-stuck-in-black-screen-after-launcher

The wiki is open for public contributions, so feel free to add something anytime you like.
