### ISSUE TITLE
Games locks up my system after few minutes

### ISSUE THREAD

**Issue by Haxk20** [redmcg/wine#4]
Hi. I started using your version of proton and it runs very very nice. But big issue i have is that the game freezes my system and i have to do hard shutdown after about 10-20 minutes.
I dont know what info do you need. So please ask for what you need. Im happy to help.
And isnt this somehow releated to the multithreaded bug ? Or this is the bug ? I havent tried playing on one core because the FPS are terrible that way.

**Comment by redmcg** [comment]
The multi-threaded bug occurs usually within minutes (often before you even get to the main menu) so this appears to be a different issue.

If you can't even access a TTY, or SSH in to your machine, then this seems like a hardware lock (due to faulty hardware or a dodgy driver).

You can try capturing a Wine log and sending me just the end of it (as a complete 20 minute log will be too big). It might also be worth experimenting with a different graphics driver.

**Comment by Haxk20** [comment]
> The multi-threaded bug occurs usually within minutes (often before you even get to the main menu) so this appears to be a different issue.
> 
> If you can't even access a TTY, or SSH in to your machine, then this seems like a hardware lock (due to faulty hardware or a dodgy driver).
> 
> You can try capturing a Wine log and sending me just the end of it (as a complete 20 minute log will be too big). It might also be worth experimenting with a different graphics driver.

I cant access TTY after it freezes. There was one issue on Ryzen Raven Ridge that caused the CPU to freeze due to cstate or something like that. But i dont think this is the same issue because i never experienced lock ups before. But i may try the "fixes" they posted and see if it freezes too.

Also how do i capture wine log ?

**Comment by redmcg** [comment]
Sorry - under Proton it's called a Proton Log. The instructions can be found here:
https://github.com/ValveSoftware/Proton#runtime-config-options

**Comment by Haxk20** [comment]
[https://ufile.io/5yt7k](url) Here is the entire log. I uploaded entire log just to be sure.
I tried disabling ESYNC but it didnt help. Will try to use D3D11 instead of DXVK.

**Comment by redmcg** [comment]
That log file looks pretty similar to mine - unfortunately I can't see anything that would indicate a lock-up in there. Do you get the same problem with both `Proton 3.16-4 Beta ED` and `Proton 3.16-6 Beta ED`?

**Comment by Haxk20** [comment]
> That log file looks pretty similar to mine - unfortunately I can't see anything that would indicate a lock-up in there. Do you get the same problem with both `Proton 3.16-4 Beta ED` and `Proton 3.16-6 Beta ED`?

Yes both versions lock up. No other game locks up for me. Well to be correct Metro Last Light and 2033 Redux both crash for me. Maybe its Swap doing it. I will disable swap and try to play that way. Also i think thats not the correct log. I think i launched the game after it crashed and that may have overwritten the log again. I will make a new log once it crashes again and will not launch the game until i send you the log.

**Comment by Haxk20** [comment]
Here is the log from lock up. [https://ufile.io/fcr82](url). This seems different at the end then the last one so i hope it helps

**Comment by Haxk20** [comment]
Ah no its same at the end. Interesting. IDK what is happening now. Maybe im running out of memory ? I have 6.7Gb of RAM because i have 8GB installed but integrated VEGA 8 takes 1GB and something. Will try disabled swap.

**Comment by redmcg** [comment]
Any luck? I took a look at your latest log - and whilst this one doesn't show a clean exit - I can't see anything different towards the end of the log that isn't there in the rest of it.

What hardware are you running? Is there any chance the CPU is overheating?

**Comment by Haxk20** [comment]
> Any luck? I took a look at your latest log - and whilst this one doesn't show a clean exit - I can't see anything different towards the end of the log that isn't there in the rest of it.
> 
> What hardware are you running? Is there any chance the CPU is overheating?

Interestingly it didnt lock up for quite a while now. Been playing 2 days for about 4 hours and i didnt experience a single lock up. Maybe i was just lucky those times or maybe something fixed it actually. What i know is that steam updated 2 days ago and i didnt experience a lock up after that. Will let you know if i experience a lock up again. Lets hope i will not

**Comment by Haxk20** [comment]
Issue most likely fixed. I reccomend everybody running MESA drivers to turn on mesa cache. Fixed the issue for me and gave me stable 60fps everywhere outside stations on high.
