### ISSUE TITLE
ED never start.

### ISSUE THREAD

**Issue by daxime** [redmcg/wine#5]
Hi,
I have tried ED, the launcher work, but the game not. I tried to find the problem with no success ...

I have installed the following package from this PPA: ppa:paulo-miguel-dias/mesa
* mesa-vulkan-drivers
* mesa-vulkan-drivers:i386
* llvm-7

And made an update of all my system (Ubuntu 18.04.1).

I have tested "vulkaninfo" (after compiling the official SDK, befor it was not working. ED still not work). It returned:
	===========
	VULKAN INFO
	===========

	Vulkan Instance Version: 1.1.70

	ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
	ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
	/build/vulkan-Kbdbga/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED

My spec:
 OS: Ubuntu 18.04.1
CPU: Ryzen 5 2600
GPU: Radeon HD7850
RAM: 16 Gb

**Comment by redmcg** [comment]
If you are still getting the VK_ERROR_INITIALIZATION_FAILED error with vulkaninfo - it means vulkan isn't working on your machine with your current setup. Unfortunately I'm not familiar with AMD drivers (I've only used Nvidia) so I can't really offer any advice (I don't even know if the HD7850 has vulkan support with Padoka drivers).

You might need to ask around on AMD or Ubuntu forums for help (or hope someone else finds this issue and can offer greater assistance than I can).

If you do find a resolution I'd be grateful if you could provide the solution here (for me and any else who stumbles across this). Cheers.

**Comment by Haxk20** [comment]
Im running AMD only system. Which version of mesa are you using ? Please check if you have vulkan-icd-loader installed on your system.
Its possible that you dont have some package missing still.
I cant tell you which one exactly because i dont use Ubuntu but Arch linux with LLVM8 and mesa-git which has all packages in 1 and ubuntu doesnt have the same package names as Arch linux.
Its very much possible that your GPU isnt supported by Padoka mesa.
But i know your GPU supports Vulkan.
If you know your way around linux you can install arch linux or Antergos and add llvm-git repository and install mesa-git from AUR.

**Comment by daxime** [comment]
Good evening,
I broke Ubuntu yesterday trying to find a solution.

I will reinstall the system and reinstall my programs and drivers. For the moment I have some small problems with the connection but I will come back as soon as everything is back in working order.

Before the crash, Mesa 18.3 was installed. I don't think Arch is for me, because i'm noob in Linux.

**Comment by daxime** [comment]
It work :D

After some research, I found a solution to the problem. By default, Ubuntu still use the Radeon driver and not AMDGPU.

```
lspci -k | grep -EA3 'VGA|3D|Display'

08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Pitcairn PRO [Radeon HD 7850 / R7 265 / R9 270 1024SP]
	Subsystem: PC Partner Limited / Sapphire Technology Radeon HD 7850 2GB GDDR5 DVI-I/DVI-D/HDMI/DP
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu
```

First, I modified the GRUB.
`sudo gedit /etc/default/grub`

Change this line:
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"`

To this :
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash radeon.si_support=0 amdgpu.si_support=1"`

Next, edit xorg.conf:
`sudo gedit /etc/X11/xorg.conf`

Then add:
```
Section "Device"
    Identifier "AMD"
    Driver "amdgpu"
    Option "TearFree" "true"
EndSection
```

And finally, blacklist radeon:
`sudo gedit /etc/modprobe.d/blacklist.conf`

Add this:
```
#GPU
blacklist radeon
```

Update GRUB and initramfs
`sudo update-grub sudo update-initramfs -u`

Reboot and that's it, problem solve.

Verify:
```
lspci -k | grep -EA3 'VGA|3D|Display'

08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Pitcairn PRO [Radeon HD 7850 / R7 265 / R9 270 1024SP]
	Subsystem: PC Partner Limited / Sapphire Technology Radeon HD 7850 2GB GDDR5 DVI-I/DVI-D/HDMI/DP
	Kernel driver in use: amdgpu
	Kernel modules: radeon, amdgpu
```

We can see that amdgpu is used by default now! There are still problems (in the game menu and keybord layout), but I suppose that is normal and will be fixed in the future.

Thank you for your work :+1: 

**UPDATE:** Modify only the GRUB works for me, the other steps seem to be not necessary.

[source](https://forum.level1techs.com/t/vulkan-with-amds-gcn-1-0/131427)

**Comment by regulator-g** [comment]
Hey Daxime I had the same issue and your fix worked, thanks. I think a lot of people would have this same problem do we need to raise it with the guys making the padoka vulkan driver?

**Comment by daxime** [comment]
I'm glad it helped you :)

I don't know much about it, but I don't think the problem comes from Vulkan. Since modifying the GRUB fix the problem, it must be a file update problem.
